[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_id_contract = "F2KMtCzRhtG5kvc9R4Av37GCrhGzjDLbrE9TwEJcdozm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/Users/tonywu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
